package application.view;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;

import application.Main;
import javafx.event.ActionEvent;

import javafx.scene.control.MenuBar;

import javafx.scene.control.Label;

import javafx.scene.control.DatePicker;
import javafx.scene.control.Button;

public class DoctorController {
	@FXML
	private DatePicker date_start;
	@FXML
	private DatePicker date_end;
	@FXML
	private TextField time_start;
	@FXML
	private TextField time_end;
	@FXML
	private MenuBar menu;
	@FXML
	private Label lb_doctorname;
	@FXML
	private AnchorPane datePane;
	@FXML
	private Button btn_choose;
 	
	private Main main;
	private TableDoctorController controller;

	// Event Listener on MenuItem.onAction
	@FXML
	public void registertable(ActionEvent event) {
		// TODO Autogenerated
		main.tableRegisterLoad();
		datePane.setVisible(false);
		btn_choose.setVisible(false);
		
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void incomeTable(ActionEvent event) {
		// TODO Autogenerated
		setcontroller(main.tableIncomeLoad());
		datePane.setVisible(true);
		btn_choose.setVisible(true);
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void myexit(ActionEvent event) {
		// TODO Autogenerated
		Main.primaryStage.close();
	}
	
	@FXML
	public void chooseincome() {
		// TODO Autogenerated
		//选择合适的收入进行显示，set一个条件，然后进行一次refresh
		
		SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
		String begindate = date_start.getValue()==null||date_start.getValue().toString().equals("")? 
				dateFormat.format(new Date()):date_start.getValue().toString();
		String begintime = time_start.getText().equals("")? "0:00:00": time_start.getText();
		String endtime = time_end.getText().equals("")? "0:00:00": time_end.getText();
		String enddate = date_end.getValue()==null||date_end.getValue().toString().equals("")?
				dateFormat.format(new Date()): date_end.getValue().toString();
		
		controller.SetDateTime(begindate + " " + begintime, enddate + " " + endtime);
//		System.out.println(date_start.getValue().toString());
//		System.out.println(time_start.getText());
//		System.out.println(date_end.getValue().toString());
//		System.out.println(time_end.getText());
		controller.superloadData();
	}
	
	@FXML
	public void initialize() {
		// TODO Auto-generated method stub
		lb_doctorname.setText(main.d.getName());
		time_start.setText("0:00:00");
		time_end.setText("0:00:00");
	}
	
	public void setMain(Main main) {
		this.main = main;
	}
	
	public void setcontroller(TableDoctorController controller) {
		this.controller = controller;
		date_start.setPromptText(controller.mydateFormat.format(new Date()));
		date_end.setPromptText(controller.mydateFormat.format(new Date()));
	}
}
